### ISSUE TITLE
Have little helper variable to know what is the lunar local time.

### ISSUE THREAD

**Issue by slosar** [lusee-night/opsim#24]
It would be very good to know where in the lunar cycle are we. `self.clock` is mjd which is useful. We also need:

* `self.lunar_clock` which is 12.0 at lunar noon and 0 at lunar midnight.
* `self.lunar_clock_sunrise` and `self_lunar_clock_sunset` which tell you the time of sunrise and sunset in these units

We need these at minimum to implement the lunar ground temperature look-up.

**Comment by buddhasystem** [comment]
Clock implemented in the branch "sim_ng". Test plots added to the "datacheck" notebook.

**Comment by buddhasystem** [comment]
All merged into main by now. Closing out.

**Comment by buddhasystem** [comment]
Merged, closing the issue.
