### ISSUE TITLE
Revise solar panels with departures from cosine law

### ISSUE THREAD

**Issue by slosar** [lusee-night/opsim#39]
Paul O'Connor knows more.

**Comment by benjamin-saliwanchik** [comment]
Added new function pv_angle_corr() to panels.py which applies a correction to the PV power to account for the measured divergence from the expected cosine law as a function of solar angle. Correction factor is implemented as a polynomial function of angle. Tested in opsim.ipynb. Power over time and total accumulated energy look correct. I think this is ready to merge back into opsim main.
